# GitHub Sponsors Configuration
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
# github: [aKs030]

# Ko-fi
# ko_fi: abdulkerimsesli

# Custom sponsorship URL
custom: ['https://www.abdulkerimsesli.de/contact/']
