self.addEventListener("install", event => {
  // ...existing code...
  console.log("Service Worker wird installiert");
  // ...existing code...
});

self.addEventListener("activate", event => {
  console.log("Service Worker ist aktiv");
  // ...existing code...
});

self.addEventListener("fetch", event => {
  // ...existing code...
  console.log("Service Worker fetch:", event.request.url);
  // ...existing code...
});