/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 32b2519aef655fbfd8c75ef9837e2f61)
interface __BaseEnv_Env {
  RATE_LIMIT_KV: KVNamespace;
  JULES_MEMORY_KV: KVNamespace;
  SITEMAP_CACHE_KV: KVNamespace;
  GALLERY_BUCKET: R2Bucket;
  DB_LIKES: D1Database;
  JULES_MEMORY: VectorizeIndex;
  AI: Ai;
  MAX_SEARCH_RESULTS: "10";
  ROBOT_CHAT_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
  ROBOT_EMBEDDING_MODEL: "@cf/baai/bge-base-en-v1.5";
  ROBOT_IMAGE_MODEL: "@cf/llava-hf/llava-1.5-7b-hf";
  ROBOT_MAX_TOKENS: "2048";
  ROBOT_MAX_HISTORY_TURNS: "10";
  ROBOT_MEMORY_TOP_K: "5";
  ROBOT_MEMORY_SCORE_THRESHOLD: "0.65";
  CONTACT_EMAIL: "krm19030@gmail.com";
  TURNSTILE_SITE_KEY: "0x4AAAAAAD8pNEcRUhm2oCBU";
  COMMENT_BLOCKLIST: "";
  COMMENT_NOTIFICATION_EMAIL: "";
  YOUTUBE_CHANNEL_ID: "UCTGRherjM4iuIn86xxubuPg";
  ALLOWED_ORIGINS: "https://abdulkerimsesli.de,https://www.abdulkerimsesli.de";
}
declare namespace Cloudflare {
  interface ProductionEnv {
    RATE_LIMIT_KV: KVNamespace;
    JULES_MEMORY_KV: KVNamespace;
    SITEMAP_CACHE_KV: KVNamespace;
    GALLERY_BUCKET: R2Bucket;
    DB_LIKES: D1Database;
    JULES_MEMORY: VectorizeIndex;
    AI: Ai;
    MAX_SEARCH_RESULTS: "10";
    ROBOT_CHAT_MODEL: "@cf/meta/llama-3.3-70b-instruct-fp8-fast";
    ROBOT_EMBEDDING_MODEL: "@cf/baai/bge-base-en-v1.5";
    ROBOT_IMAGE_MODEL: "@cf/llava-hf/llava-1.5-7b-hf";
    ROBOT_MAX_TOKENS: "2048";
    ROBOT_MAX_HISTORY_TURNS: "10";
    ROBOT_MEMORY_TOP_K: "5";
    ROBOT_MEMORY_SCORE_THRESHOLD: "0.65";
    CONTACT_EMAIL: "krm19030@gmail.com";
    TURNSTILE_SITE_KEY: "0x4AAAAAAD8pNEcRUhm2oCBU";
    COMMENT_BLOCKLIST: "";
    COMMENT_NOTIFICATION_EMAIL: "";
    YOUTUBE_CHANNEL_ID: "UCTGRherjM4iuIn86xxubuPg";
    ALLOWED_ORIGINS: "https://abdulkerimsesli.de,https://www.abdulkerimsesli.de";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "MAX_SEARCH_RESULTS"
      | "ROBOT_CHAT_MODEL"
      | "ROBOT_EMBEDDING_MODEL"
      | "ROBOT_IMAGE_MODEL"
      | "ROBOT_MAX_TOKENS"
      | "ROBOT_MAX_HISTORY_TURNS"
      | "ROBOT_MEMORY_TOP_K"
      | "ROBOT_MEMORY_SCORE_THRESHOLD"
      | "CONTACT_EMAIL"
      | "TURNSTILE_SITE_KEY"
      | "COMMENT_BLOCKLIST"
      | "COMMENT_NOTIFICATION_EMAIL"
      | "YOUTUBE_CHANNEL_ID"
      | "ALLOWED_ORIGINS"
    >
  > {}
}
