/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3a06348eb79dfe9aed751c18918537ed)
declare namespace Cloudflare {
  interface ProductionEnv {
    RATE_LIMIT_KV: KVNamespace;
    SITEMAP_CACHE_KV: KVNamespace;
    GALLERY_BUCKET: R2Bucket;
    AI: Ai;
    JULES_MEMORY: VectorizeIndex;
  }
  interface Env {
    RATE_LIMIT_KV: KVNamespace;
    SITEMAP_CACHE_KV: KVNamespace;
    GALLERY_BUCKET: R2Bucket;
    AI: Ai;
    JULES_MEMORY: VectorizeIndex;
    MAX_SEARCH_RESULTS?: '10';
    RAG_ID?: 'wispy-pond-1055';
    AI_SEARCH_MAX_RESULTS?: '10';
    AI_SEARCH_CONTEXT_MAX_RESULTS?: '6';
    AI_SEARCH_SCORE_THRESHOLD?: '0.25';
    AI_SEARCH_REWRITE_QUERY?: 'true';
    AI_SEARCH_RERANKING_ENABLED?: 'true';
    AI_SEARCH_RERANKING_MODEL?: '@cf/baai/bge-reranker-base';
    CONTACT_EMAIL?: 'krm19030@gmail.com';
    YOUTUBE_CHANNEL_ID?: 'UCTGRherjM4iuIn86xxubuPg';
    ALLOWED_ORIGINS?: 'https://abdulkerimsesli.de,https://www.abdulkerimsesli.de';
  }
}
interface Env extends Cloudflare.Env {}
