/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fa7ec4fc447420da5863c8d060e27326)
declare namespace Cloudflare {
  interface ProductionEnv {
    RATE_LIMIT_KV: KVNamespace;
    SITEMAP_CACHE_KV: KVNamespace;
    GALLERY_BUCKET: R2Bucket;
    JULES_MEMORY: VectorizeIndex;
    AI: Ai;
    GROQ_API_KEY: string;
  }
  interface Env {
    GROQ_API_KEY: string;
    RATE_LIMIT_KV: KVNamespace;
    SITEMAP_CACHE_KV: KVNamespace;
    GALLERY_BUCKET: R2Bucket;
    JULES_MEMORY: VectorizeIndex;
    AI: Ai;
    MAX_SEARCH_RESULTS?: '10';
    RAG_ID?: 'wispy-pond-1055';
    AI_SEARCH_MAX_RESULTS?: '10';
    AI_SEARCH_CONTEXT_MAX_RESULTS?: '6';
    AI_SEARCH_SCORE_THRESHOLD?: '0.25';
    AI_SEARCH_REWRITE_QUERY?: 'true';
    AI_SEARCH_RERANKING_ENABLED?: 'true';
    AI_SEARCH_RERANKING_MODEL?: '@cf/baai/bge-reranker-base';
    ROBOT_CHAT_MODEL?: '@cf/meta/llama-3.3-70b-instruct-fp8-fast';
    ROBOT_EMBEDDING_MODEL?: '@cf/baai/bge-base-en-v1.5';
    ROBOT_IMAGE_MODEL?: '@cf/llava-hf/llava-1.5-7b-hf';
    ROBOT_MAX_TOKENS?: '2048';
    ROBOT_MAX_HISTORY_TURNS?: '10';
    ROBOT_MEMORY_TOP_K?: '5';
    ROBOT_MEMORY_SCORE_THRESHOLD?: '0.65';
    CONTACT_EMAIL?: 'krm19030@gmail.com';
    YOUTUBE_CHANNEL_ID?: 'UCTGRherjM4iuIn86xxubuPg';
    ALLOWED_ORIGINS?: 'https://abdulkerimsesli.de,https://www.abdulkerimsesli.de';
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | 'GROQ_API_KEY'
      | 'MAX_SEARCH_RESULTS'
      | 'RAG_ID'
      | 'AI_SEARCH_MAX_RESULTS'
      | 'AI_SEARCH_CONTEXT_MAX_RESULTS'
      | 'AI_SEARCH_SCORE_THRESHOLD'
      | 'AI_SEARCH_REWRITE_QUERY'
      | 'AI_SEARCH_RERANKING_ENABLED'
      | 'AI_SEARCH_RERANKING_MODEL'
      | 'ROBOT_CHAT_MODEL'
      | 'ROBOT_EMBEDDING_MODEL'
      | 'ROBOT_IMAGE_MODEL'
      | 'ROBOT_MAX_TOKENS'
      | 'ROBOT_MAX_HISTORY_TURNS'
      | 'ROBOT_MEMORY_TOP_K'
      | 'ROBOT_MEMORY_SCORE_THRESHOLD'
      | 'CONTACT_EMAIL'
      | 'YOUTUBE_CHANNEL_ID'
      | 'ALLOWED_ORIGINS'
    >
  > {}
}
