name: Setup Node
description: Setup Node.js 22 with npm cache and install dependencies
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: npm
    - run: npm ci --prefer-offline --no-audit --no-fund
      shell: bash
