export const CONFIG = {
  EARTH: {
    RADIUS: 3.5,
    SEGMENTS: 512,
    SEGMENTS_MOBILE: 160,
    BUMP_SCALE: 0.011,
    HERO_DISPLACEMENT_SCALE: 0.018,
    DEFAULT_DISPLACEMENT_SCALE: 0,
    AMBIENT_ROTATION_SPEED: 0,
    EMISSIVE_INTENSITY: 0.2,
    EMISSIVE_PULSE_SPEED: 0.3,
    EMISSIVE_PULSE_AMPLITUDE: 0.08,
    AXIAL_TILT: -23.4,
  },
  CLOUDS: {
    ALTITUDE: 0.022,
    HIGH_ALTITUDE: 0.038,
    SHADOW_ALTITUDE: 0.008,
    SHADOW_OPACITY: 0.032,
    HIGH_OPACITY_FACTOR: 0.34,
    ROTATION_SPEED: 0.00022,
    OPACITY: 0.22,
  },
  SUN: {
    INTENSITY: 1.8,
  },
  LIGHTING: {
    DAY: {
      AMBIENT_INTENSITY: 1.4,
      AMBIENT_COLOR: 0x606060,
      SUN_INTENSITY: 1.8,
      FILL_INTENSITY: 0.28,
      RIM_INTENSITY: 0.32,
    },
    NIGHT: {
      AMBIENT_INTENSITY: 0.36,
      AMBIENT_COLOR: 0x202845,
      SUN_INTENSITY: 0.42,
      FILL_INTENSITY: 0.36,
      RIM_INTENSITY: 0.62,
    },
  },
  STARS: {
    COUNT: 4800,
    TWINKLE_SPEED: 0.34,
  },
  MOON: {
    RADIUS: 0.95,
    DISTANCE: 25,
    ORBIT_SPEED: 0.00025,
    SEGMENTS: 96,
    BUMP_SCALE: 0.028,
    DISPLACEMENT_SCALE: 0.016,
  },
  CAMERA: {
    FOV: 45,
    NEAR: 0.1,
    FAR: 1000,
    ZOOM_MIN: 5,
    ZOOM_MAX: 25,
    LERP_FACTOR: 0.06,
    PRESETS: {
      hero: {
        x: 0,
        y: 4.1,
        z: 10.8,
        lookAt: { x: 0, y: -1.5, z: 0 },
      },
      features: {
        x: 1.25,
        y: 4.55,
        z: 10.8,
        lookAt: { x: 0, y: 0, z: -0.2 },
      },
      section3: {
        x: -2.4,
        y: 3.2,
        z: 10.2,
        lookAt: { x: 0.55, y: -0.35, z: -0.4 },
      },
    },
    TRANSITION_DURATION: 1.8,
  },
  SHOOTING_STARS: {
    BASE_FREQUENCY: 0.003,
    SHOWER_FREQUENCY: 0.02,
    SHOWER_DURATION: 180,
    SHOWER_COOLDOWN: 1200,
    MAX_SIMULTANEOUS: 3,
  },
  PERFORMANCE: {
    PIXEL_RATIO: Math.min(window.devicePixelRatio || 1, 2),
  },
  QUALITY_LEVELS: {
    HIGH: {
      minFPS: 50,
      cloudLayer: true,
      highCloudLayer: true,
      terrainDetailScale: 1,
      meteorShowers: true,
      desktopPixelRatio: 2,
      mobilePixelRatio: 1.75,
    },
    MEDIUM: {
      minFPS: 28,
      cloudLayer: true,
      highCloudLayer: true,
      terrainDetailScale: 0.78,
      meteorShowers: true,
      desktopPixelRatio: 1.7,
      mobilePixelRatio: 1.45,
    },
    LOW: {
      minFPS: 0,
      cloudLayer: true,
      highCloudLayer: false,
      terrainDetailScale: 0.52,
      meteorShowers: false,
      desktopPixelRatio: 1.25,
      mobilePixelRatio: 1.1,
    },
  },
};
