export const CONFIG = {
  EARTH: {
    RADIUS: 3.5,
    SEGMENTS: 192,
    SEGMENTS_MOBILE: 112,
    HERO_DISPLACEMENT_SCALE: 0.024,
    DEFAULT_DISPLACEMENT_SCALE: 0,
    AMBIENT_ROTATION_SPEED: 0,
    CITY_LIGHT_INTENSITY: 1.35,
    AXIAL_TILT: -23.4,
  },
  CLOUDS: {
    ALTITUDE: 0.012,
    HIGH_ALTITUDE: 0.021,
    SHADOW_ALTITUDE: 0.004,
    SHADOW_OPACITY: 0.022,
    HIGH_OPACITY_FACTOR: 0.32,
    ROTATION_SPEED: 0.000065,
    OPACITY: 0.22,
  },
  SUN: {
    INTENSITY: 1.8,
  },
  LIGHTING: {
    DAY: {
      AMBIENT_INTENSITY: 1.4,
      AMBIENT_COLOR: 0x606060,
      SUN_INTENSITY: 1.8,
      FILL_INTENSITY: 0.28,
      RIM_INTENSITY: 0.32,
    },
    NIGHT: {
      AMBIENT_INTENSITY: 0.36,
      AMBIENT_COLOR: 0x202845,
      SUN_INTENSITY: 0.42,
      FILL_INTENSITY: 0.36,
      RIM_INTENSITY: 0.62,
    },
  },
  STARS: {
    COUNT: 3600,
    TWINKLE_SPEED: 0.34,
  },
  MOON: {
    RADIUS: 0.95,
    DISTANCE: 25,
    ORBIT_SPEED: 0.00025,
    SEGMENTS: 96,
    BUMP_SCALE: 0.028,
    DISPLACEMENT_SCALE: 0.016,
  },
  CAMERA: {
    FOV: 45,
    NEAR: 0.1,
    FAR: 1000,
    ZOOM_MIN: 5,
    ZOOM_MAX: 25,
    LERP_FACTOR: 0.06,
    PRESETS: {
      hero: {
        x: 0,
        y: 4.1,
        z: 10.8,
        fov: 45,
        lookAt: { x: 0, y: -1.5, z: 0 },
      },
      features: {
        x: 0.42,
        y: 3.65,
        z: 11.55,
        fov: 40,
        lookAt: { x: 0, y: -1.05, z: -1.15 },
      },
      section3: {
        // Keep Section 2 distance/FOV; the sideways perspective comes from camera orbit.
        x: 0.42,
        y: 3.65,
        z: 11.55,
        fov: 40,
        lookAt: { x: 0, y: -1.05, z: -1.15 },
      },
    },
    TRANSITION_DURATION: 2.45,
  },
  SHOOTING_STARS: {
    BASE_FREQUENCY: 0.003,
    MAX_SIMULTANEOUS: 3,
  },
  PERFORMANCE: {
    PIXEL_RATIO: Math.min(globalThis.devicePixelRatio || 1, 2),
  },
  QUALITY_LEVELS: {
    HIGH: {
      minFPS: 50,
      cloudLayer: true,
      highCloudLayer: true,
      terrainDetailScale: 1,
      meteorShowers: true,
      desktopPixelRatio: 2,
      mobilePixelRatio: 1.75,
    },
    MEDIUM: {
      minFPS: 28,
      cloudLayer: true,
      highCloudLayer: false,
      terrainDetailScale: 0.78,
      meteorShowers: true,
      desktopPixelRatio: 1.7,
      mobilePixelRatio: 1.45,
    },
    LOW: {
      minFPS: 0,
      cloudLayer: true,
      highCloudLayer: false,
      terrainDetailScale: 0.52,
      meteorShowers: false,
      desktopPixelRatio: 1.25,
      mobilePixelRatio: 1.1,
    },
  },
};
