name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Dependencies
        run: npm install


      - name: Build Site
        run: npm run build

      - name: Run QA (Lint, HTML-Validate, Lighthouse)
        run: |
          npm run lint || echo "no lint"
          npm run validate-html || echo "no validate"
          npm run lighthouse-ci || echo "no lhci"



      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: iweb
          directory: .