name: HTML Validation & Quality Checks

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: HTML Validation
        run: |
          set -o pipefail
          npm run lint:html | tee validation-html.txt

      - name: CSS Consolidation Check
        run: |
          set -o pipefail
          npm run check:css | tee validation-css.txt

      - name: JavaScript Linting
        run: |
          set -o pipefail
          npm run lint:js | tee validation-eslint.txt

      - name: Upload validation results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results-${{ github.run_number }}
          path: |
            validation-html.txt
            validation-css.txt
            validation-eslint.txt
          retention-days: 7
