name: Remove Service Worker (final)

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "Bestätige mit YES, um sw.js endgültig zu löschen"
        required: true
        default: "NO"

permissions:
  contents: write

jobs:
  remove-sw:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Sicherheitscheck – keine SW-Registrierung im Code
        run: |
          if git grep -nE "navigator\.serviceWorker\.register|/sw\.js" -- ':!sw.js' ':!**/.github/workflows/**' | grep -v "tombstone"; then
            echo "Es gibt noch Code, der den Service Worker registriert. Abbruch." >&2
            exit 1
          fi

      - name: Sicherheitscheck – sw.js ist Tombstone
        run: |
          if ! grep -q "Tombstone Service Worker" sw.js; then
            echo "sw.js ist nicht der erwartete Tombstone. Abbruch." >&2
            exit 1
          fi

      - name: Entferne Datei sw.js
        run: |
          git rm -f sw.js

      - name: Entferne Inline-Unregister aus index.html
        shell: bash
        run: |
          awk 'BEGIN{skip=0} /<!-- Entferne evtl. vorhandene Service Worker und zugehörige Caches \(schnell & inline\) -->/{skip=1; next} skip && /<\/script>/{skip=0; next} !skip {print}' index.html > index.html.tmp && mv index.html.tmp index.html

      - name: Entferne Decommission-Block aus main.js
        run: |
          node -e "const fs=require('fs'); const p='content/webentwicklung/main.js'; let s=fs.readFileSync(p,'utf8'); const before=s; s=s.replace(/\\/\\/ ===== Service Worker Entfernung \\(Decommission\\) [\\s\\S]*?(?=\\n\\/\\/ ===== )/,''); if(before!==s){ fs.writeFileSync(p,s); } else { console.log('Hinweis: Decommission-Block nicht gefunden oder bereits entfernt.'); }"

      - name: README aktualisieren
        run: |
          node -e "const fs=require('fs'); const p='README.md'; let s=fs.readFileSync(p,'utf8'); s=s.replace('Service Worker entfernt (Nov 2025)','Service Worker vollständig entfernt (Nov 2025)'); if(!/Service Worker vollständig entfernt/.test(s)){ s += '\n\n## Hinweis: Service Worker vollständig entfernt (Nov 2025)\n'; } fs.writeFileSync(p,s);"

      - name: Commit & Push
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "Keine Änderungen zu committen."
            exit 0
          fi
          git commit -m "chore: remove sw.js and cleanup unregister helpers (final)"
          git push
